import {
  FaGoogle,
  FaUser,
  FaLock,
  FaEnvelope,
  FaHome,
  FaBook,
  FaCalendar,
  FaBell,
  FaCog,
  FaSignOutAlt,
  FaMoon,
  FaSun,
  FaSearch,
  FaPlus,
  FaEdit,
  FaTrash,
  FaCheck,
  FaTimes,
  FaInfoCircle,
  FaExclamationTriangle,
  FaQuestionCircle,
} from 'react-icons/fa';

export const icons = {
  google: FaGoogle,
  user: FaUser,
  lock: FaLock,
  envelope: FaEnvelope,
  home: FaHome,
  book: FaBook,
  calendar: FaCalendar,
  bell: FaBell,
  cog: FaCog,
  signOut: FaSignOutAlt,
  moon: FaMoon,
  sun: FaSun,
  search: FaSearch,
  plus: FaPlus,
  edit: FaEdit,
  trash: FaTrash,
  check: FaCheck,
  times: FaTimes,
  info: FaInfoCircle,
  warning: FaExclamationTriangle,
  question: FaQuestionCircle,
}; 